
# Where things are
source:      .
destination: ./_site
layouts:     ./blog/_layouts
posts:     ./blog/_posts
plugins:     ./blog/_plugins
plugins:     ./drafts/_drafts

name: "traviso.js"
exclude: ["asset_sources", "less"]
timezone: "Europe/London"
safe: true
lsi: false
host: localhost
port: 4001
description: Traviso is an open source JS engine that makes it easy to build isometric applications that run in a web browser
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments
url: http://www.travisojs.com
excerpt_separator: <!--more-->

redcarpet:
  extensions: ["space_after_headers", "quote", "hard_wrap", "lax_spacing"]
